### ISSUE TITLE
Use node compiler instead of typst-ts-cli

### ISSUE THREAD

**Issue by Myriad-Dreamin** [dark-flames/apollo-typst#1]
Like that [hexo-renderer-typst/lib/compiler.cjs](https://github.com/Myriad-Dreamin/typst.ts/blob/cc868531c97393ac9d5d32fc59868eac6e16e356/projects/hexo-renderer-typst/lib/compiler.cjs), as well as [Documentation](https://myriad-dreamin.github.io/typst.ts/cookery/guide/all-in-one-node.html).

```js
const { NodeCompiler, DynLayoutCompiler } = require('@myriaddreamin/typst-ts-node-compiler');
const regularCompiler = NodeCompiler.create();
const dynLayout = DynLayoutCompiler.fromBoxed(regularCompiler.intoBoxed())；
return dynLayout.vector({ mainFilePath });;
```

**Comment by dark-flames** [comment]
I'm currently working on a new CLI entry instead of the `typst-ts-cli`, as I noticed that the --input argument becomes invalid when compiling to a dynamic layout.

**Comment by Myriad-Dreamin** [comment]
I managed to make it work in my fork, https://github.com/Myriad-Dreamin/apollo-typst.

**Comment by dark-flames** [comment]
I'm considering developing a new CLI entry in Rust to provide more flexible functionality. It will become a fully-featured static site generator based on Zola, and will support various content types, not just Markdown and Typst. This work might take some time.

**Comment by dark-flames** [comment]
> I managed to make it work in my fork, https://github.com/Myriad-Dreamin/apollo-typst.

I have cherry-picked commits from your repository. Thank you for your contributions.

**Comment by Myriad-Dreamin** [comment]
I guess this is not needed anymore.

https://github.com/dark-flames/apollo-typst/blob/a1db06f99f7d907eb8740c6f5c9a5e33b41be71f/README.md?plain=1#L16
